name: prometheus_client
description: Dart implementation of the Prometheus client library providing metrics.
version: 0.4.0+4
homepage: https://github.com/tentaclelabs/prometheus_client

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  collection: ^1.14.11

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
