name: prometheus_client
description: Dart implementation of the Prometheus client library providing metrics.
version: 1.0.0+1
homepage: https://github.com/tentaclelabs/prometheus_client

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
