name: (prometheus_client_shelf) Publish package

on:
  release:
    types: [published]
  push:
    branches:
      - master
  pull_request:

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@7112915a1a834881d4c98ef7af12f3456e5c79c7
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: false
          skip_test: true
          package_directory: './prometheus_client_shelf/'
          dry_run: ${{ !github.event.release }}
