name: (prometheus_client) Dart CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2.3.2
    - name: Install dependencies
      working-directory: ./prometheus_client
      run: pub get
    - name: Run tests
      working-directory: ./prometheus_client
      run: pub run test
    - name: (prometheus_client) Dart/Flutter Package Analyzer
      uses: axel-op/dart_package_analyzer@v3
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        relativePath: prometheus_client/
